def cacti_moving_0(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() > 4:
		till()
		till()
		plant(Entities.Cactus)
	move(North)
	cacti_moving_1(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_moving_1(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() > 4:
		till()
		till()
		plant(Entities.Cactus)
	SouthSorting()
	move(East)
	cacti_moving_2(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_moving_2(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() > 4:
		till()
		till()
		plant(Entities.Cactus)
	WestSorting()
	move(North)
	cacti_moving_3(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_moving_3(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() > 4:
		till()
		till()
		plant(Entities.Cactus)
	SouthSorting()
	move(East)
	cacti_moving_4(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_moving_4(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() > 4:
		till()
		till()
		plant(Entities.Cactus)
	WestSorting()
	move(North)
	cacti_moving_5(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_moving_5(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() > 5:
		till()
		till()
		plant(Entities.Cactus)
	SouthSorting()
	move(East)
	cacti_moving_6(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_moving_6(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() > 5:
		till()
		till()
		plant(Entities.Cactus)
	WestSorting()
	move(North)
	cacti_moving_7(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_moving_7(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() > 6:
		till()
		till()
		plant(Entities.Cactus)
	SouthSorting()
	move(East)
	cacti_moving_8(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_moving_8(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() > 7:
		till()
		till()
		plant(Entities.Cactus)
	WestSorting()
	move(North)
	cacti_moving_9(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_moving_9(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	SouthSorting()
	move(East)
	cacti_moving_10(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_moving_10(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() < 1:
		till()
		till()
		plant(Entities.Cactus)
	WestSorting()
	move(North)
	cacti_moving_11(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_moving_11(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() < 2:
		till()
		till()
		plant(Entities.Cactus)
	SouthSorting()
	move(East)
	cacti_moving_12(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_moving_12(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() < 3:
		till()
		till()
		plant(Entities.Cactus)
	WestSorting()
	move(North)
	cacti_moving_13(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_moving_13(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() < 4:
		till()
		till()
		plant(Entities.Cactus)
	SouthSorting()
	move(East)
	cacti_moving_14(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_moving_14(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() < 4:
		till()
		till()
		plant(Entities.Cactus)
	WestSorting()
	move(North)
	cacti_moving_15(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_moving_15(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() < 5:
		till()
		till()
		plant(Entities.Cactus)
	SouthSorting()
	move(East)
	cacti_moving_16(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_moving_16(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() < 5:
		till()
		till()
		plant(Entities.Cactus)
	WestSorting()
	move(North)
	cacti_moving_17(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_moving_17(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() < 5:
		till()
		till()
		plant(Entities.Cactus)
	SouthSorting()
	move(West)
	cacti_moving_18(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_moving_18(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() < 5:
		till()
		till()
		plant(Entities.Cactus)
	SouthEastSorting()
	move(West)
	cacti_moving_19(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_moving_19(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() < 5:
		till()
		till()
		plant(Entities.Cactus)
	EastSorting()
	move(South)
	cacti_moving_20(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_moving_20(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() < 4:
		till()
		till()
		plant(Entities.Cactus)
	NorthEastSouthSorting()
	grid7[8] = measure(East)
	move(West)
	cacti_moving_21(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_moving_21(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() < 4:
		till()
		till()
		plant(Entities.Cactus)
	EastSorting()
	grid6[8] = measure(East)
	move(South)
	cacti_moving_22(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_moving_22(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() < 3:
		till()
		till()
		plant(Entities.Cactus)
	NorthEastSouthSorting()
	grid6[7] = measure(East)
	move(West)
	cacti_moving_23(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_moving_23(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() < 2:
		till()
		till()
		plant(Entities.Cactus)
	EastSorting()
	grid5[7] = measure(East)
	move(South)
	cacti_moving_24(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_moving_24(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() < 1:
		till()
		till()
		plant(Entities.Cactus)
	NorthEastSouthSorting()
	grid5[6] = measure(East)
	move(West)
	cacti_moving_25(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_moving_25(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	EastSorting()
	grid4[6] = measure(East)
	move(South)
	cacti_moving_26(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_moving_26(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() > 7:
		till()
		till()
		plant(Entities.Cactus)
	NorthEastSouthSorting()
	grid4[5] = measure(East)
	move(West)
	cacti_moving_27(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_moving_27(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() > 6:
		till()
		till()
		plant(Entities.Cactus)
	EastSorting()
	grid3[5] = measure(East)
	move(South)
	cacti_moving_28(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_moving_28(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() > 5:
		till()
		till()
		plant(Entities.Cactus)
	NorthEastSouthSorting()
	grid3[4] = measure(East)
	move(West)
	cacti_moving_29(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_moving_29(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() > 5:
		till()
		till()
		plant(Entities.Cactus)
	EastSorting()
	grid2[4] = measure(East)
	move(South)
	cacti_moving_30(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_moving_30(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() > 4:
		till()
		till()
		plant(Entities.Cactus)
	NorthEastSouthSorting()
	grid2[3] = measure(East)
	move(West)
	cacti_moving_31(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_moving_31(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() > 4:
		till()
		till()
		plant(Entities.Cactus)
	EastSorting()
	move(South)
	cacti_moving_32(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_moving_32(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() > 4:
		till()
		till()
		plant(Entities.Cactus)
	NorthEastSouthSorting()
	grid1[2] = measure(East)
	move(North)
	cacti_moving_33(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_moving_33(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	SouthEastSorting()
	grid1[3] = measure(East)
	move(North)
	cacti_moving_34(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_moving_34(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() > 4:
		till()
		till()
		plant(Entities.Cactus)
	SouthEastSorting()
	move(North)
	cacti_moving_35(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_moving_35(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() > 5:
		till()
		till()
		plant(Entities.Cactus)
	SouthSorting()
	move(East)
	cacti_moving_36(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_moving_36(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() > 5:
		till()
		till()
		plant(Entities.Cactus)
	EastSouthWestSorting()
	grid1[4] = measure(South)
	move(North)
	cacti_moving_37(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_moving_37(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() > 6:
		till()
		till()
		plant(Entities.Cactus)
	SouthSorting()
	grid1[5] = measure(South)
	move(East)
	cacti_moving_38(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_moving_38(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() > 7:
		till()
		till()
		plant(Entities.Cactus)
	EastSouthWestSorting()
	grid2[5] = measure(South)
	move(North)
	cacti_moving_39(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_moving_39(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	SouthSorting()
	grid2[6] = measure(South)
	move(East)
	cacti_moving_40(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_moving_40(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() < 1:
		till()
		till()
		plant(Entities.Cactus)
	EastSouthWestSorting()
	grid3[6] = measure(South)
	move(North)
	cacti_moving_41(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_moving_41(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() < 2:
		till()
		till()
		plant(Entities.Cactus)
	SouthSorting()
	grid3[7] = measure(South)
	move(East)
	cacti_moving_42(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_moving_42(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() < 3:
		till()
		till()
		plant(Entities.Cactus)
	EastSouthWestSorting()
	grid4[7] = measure(South)
	move(North)
	cacti_moving_43(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_moving_43(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() < 4:
		till()
		till()
		plant(Entities.Cactus)
	SouthSorting()
	move(East)
	cacti_moving_44(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_moving_44(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() < 4:
		till()
		till()
		plant(Entities.Cactus)
	EastSouthWestSorting()
	grid5[8] = measure(South)
	move(West)
	cacti_moving_45(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_moving_45(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	SouthEastSorting()
	grid4[8] = measure(South)
	move(West)
	cacti_moving_46(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_moving_46(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() < 3:
		till()
		till()
		plant(Entities.Cactus)
	SouthEastSorting()
	move(West)
	cacti_moving_47(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_moving_47(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() < 2:
		till()
		till()
		plant(Entities.Cactus)
	EastSorting()
	move(South)
	cacti_moving_48(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_moving_48(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() < 1:
		till()
		till()
		plant(Entities.Cactus)
	NorthEastSouthSorting()
	grid3[8] = measure(East)
	move(West)
	cacti_moving_49(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_moving_49(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	EastSorting()
	move(South)
	cacti_moving_50(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_moving_50(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() > 7:
		till()
		till()
		plant(Entities.Cactus)
	NorthEastSouthSorting()
	grid2[7] = measure(East)
	move(West)
	cacti_moving_51(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_moving_51(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() > 6:
		till()
		till()
		plant(Entities.Cactus)
	EastSorting()
	move(South)
	cacti_moving_52(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_moving_52(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() > 5:
		till()
		till()
		plant(Entities.Cactus)
	NorthEastSouthSorting()
	grid1[6] = measure(East)
	move(North)
	cacti_moving_53(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_moving_53(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	SouthEastSorting()
	move(North)
	cacti_moving_54(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_moving_54(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() > 7:
		till()
		till()
		plant(Entities.Cactus)
	SouthEastSorting()
	move(East)
	cacti_moving_55(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_moving_55(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	EastSouthWestSorting()
	grid2[8] = measure(East)
	grid1[7] = measure(South)
	move(North)
	cacti_moving_56(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_moving_56(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() < 1:
		till()
		till()
		plant(Entities.Cactus)
	SouthEastSorting()
	grid1[8] = measure(South)
	move(West)
	cacti_moving_57(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_moving_57(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	SouthEastSorting()
	move(West)
	cacti_moving_58(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_moving_58(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() < 5:
		till()
		till()
		plant(Entities.Cactus)
	WestSorting()
	grid0[9] = measure(East)
	move(South)
	cacti_moving_59(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_moving_59(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() < 5:
		till()
		till()
		plant(Entities.Cactus)
	NorthWestSorting()
	grid0[8] = measure(East)
	move(South)
	cacti_moving_60(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_moving_60(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() < 5:
		till()
		till()
		plant(Entities.Cactus)
	NorthSorting()
	grid0[7] = measure(East)
	grid9[8] = measure(North)
	move(West)
	cacti_moving_61(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_moving_61(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() < 5:
		till()
		till()
		plant(Entities.Cactus)
	WestNorthEastSorting()
	grid8[8] = measure(North)
	move(South)
	cacti_moving_62(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_moving_62(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() < 4:
		till()
		till()
		plant(Entities.Cactus)
	NorthSorting()
	grid8[7] = measure(North)
	move(West)
	cacti_moving_63(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_moving_63(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() < 4:
		till()
		till()
		plant(Entities.Cactus)
	WestNorthEastSorting()
	grid7[7] = measure(North)
	move(South)
	cacti_moving_64(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_moving_64(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() < 3:
		till()
		till()
		plant(Entities.Cactus)
	NorthSorting()
	grid7[6] = measure(North)
	move(West)
	cacti_moving_65(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_moving_65(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() < 2:
		till()
		till()
		plant(Entities.Cactus)
	WestNorthEastSorting()
	grid6[6] = measure(North)
	move(South)
	cacti_moving_66(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_moving_66(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() < 1:
		till()
		till()
		plant(Entities.Cactus)
	NorthSorting()
	grid6[5] = measure(North)
	move(West)
	cacti_moving_67(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_moving_67(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	WestNorthEastSorting()
	grid5[5] = measure(North)
	move(South)
	cacti_moving_68(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_moving_68(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() > 7:
		till()
		till()
		plant(Entities.Cactus)
	NorthSorting()
	grid5[4] = measure(North)
	move(West)
	cacti_moving_69(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_moving_69(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() > 6:
		till()
		till()
		plant(Entities.Cactus)
	WestNorthEastSorting()
	grid4[4] = measure(North)
	move(South)
	cacti_moving_70(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_moving_70(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() > 5:
		till()
		till()
		plant(Entities.Cactus)
	NorthSorting()
	grid4[3] = measure(North)
	move(West)
	cacti_moving_71(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_moving_71(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() > 5:
		till()
		till()
		plant(Entities.Cactus)
	WestNorthEastSorting()
	grid3[3] = measure(North)
	move(South)
	cacti_moving_72(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_moving_72(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() > 4:
		till()
		till()
		plant(Entities.Cactus)
	NorthSorting()
	grid3[2] = measure(North)
	move(West)
	cacti_moving_73(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_moving_73(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() > 4:
		till()
		till()
		plant(Entities.Cactus)
	WestNorthEastSorting()
	grid2[2] = measure(North)
	move(South)
	cacti_moving_74(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_moving_74(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() > 4:
		till()
		till()
		plant(Entities.Cactus)
	NorthSorting()
	move(West)
	cacti_moving_75(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_moving_75(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() > 4:
		till()
		till()
		plant(Entities.Cactus)
	WestNorthEastSorting()
	grid1[9] = measure(South)
	grid1[1] = measure(North)
	move(East)
	cacti_moving_76(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_moving_76(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	NorthWestSorting()
	grid1[0] = measure(West)
	grid2[9] = measure(South)
	grid2[1] = measure(North)
	move(East)
	cacti_moving_77(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_moving_77(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() > 4:
		till()
		till()
		plant(Entities.Cactus)
	NorthWestSorting()
	grid2[0] = measure(West)
	grid3[9] = measure(South)
	move(East)
	cacti_moving_78(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_moving_78(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() > 4:
		till()
		till()
		plant(Entities.Cactus)
	WestSorting()
	grid3[0] = measure(West)
	grid4[9] = measure(South)
	move(North)
	cacti_moving_79(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_moving_79(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() > 5:
		till()
		till()
		plant(Entities.Cactus)
	SouthWestNorthSorting()
	grid3[1] = measure(West)
	move(East)
	cacti_moving_80(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_moving_80(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() > 5:
		till()
		till()
		plant(Entities.Cactus)
	WestSorting()
	grid4[1] = measure(West)
	move(North)
	cacti_moving_81(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_moving_81(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() > 6:
		till()
		till()
		plant(Entities.Cactus)
	SouthWestNorthSorting()
	grid4[2] = measure(West)
	move(East)
	cacti_moving_82(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_moving_82(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() > 7:
		till()
		till()
		plant(Entities.Cactus)
	WestSorting()
	grid5[2] = measure(West)
	move(North)
	cacti_moving_83(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_moving_83(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	SouthWestNorthSorting()
	grid5[3] = measure(West)
	move(East)
	cacti_moving_84(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_moving_84(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() < 1:
		till()
		till()
		plant(Entities.Cactus)
	WestSorting()
	grid6[3] = measure(West)
	move(North)
	cacti_moving_85(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_moving_85(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() < 2:
		till()
		till()
		plant(Entities.Cactus)
	SouthWestNorthSorting()
	grid6[4] = measure(West)
	move(East)
	cacti_moving_86(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_moving_86(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() < 3:
		till()
		till()
		plant(Entities.Cactus)
	WestSorting()
	grid7[4] = measure(West)
	move(North)
	cacti_moving_87(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_moving_87(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() < 4:
		till()
		till()
		plant(Entities.Cactus)
	SouthWestNorthSorting()
	grid7[5] = measure(West)
	move(East)
	cacti_moving_88(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_moving_88(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() < 4:
		till()
		till()
		plant(Entities.Cactus)
	WestSorting()
	move(North)
	cacti_moving_89(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_moving_89(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() < 5:
		till()
		till()
		plant(Entities.Cactus)
	SouthWestNorthSorting()
	grid8[6] = measure(West)
	grid0[6] = measure(East)
	grid9[7] = measure(North)
	move(South)
	cacti_moving_90(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_moving_90(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	NorthWestSorting()
	grid8[5] = measure(West)
	grid0[5] = measure(East)
	grid9[6] = measure(North)
	move(South)
	cacti_moving_91(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_moving_91(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() < 4:
		till()
		till()
		plant(Entities.Cactus)
	NorthWestSorting()
	grid0[4] = measure(East)
	grid9[5] = measure(North)
	move(South)
	cacti_moving_92(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_moving_92(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() < 3:
		till()
		till()
		plant(Entities.Cactus)
	NorthSorting()
	grid0[3] = measure(East)
	grid9[4] = measure(North)
	move(West)
	cacti_moving_93(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_moving_93(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() < 2:
		till()
		till()
		plant(Entities.Cactus)
	WestNorthEastSorting()
	grid8[4] = measure(North)
	move(South)
	cacti_moving_94(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_moving_94(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() < 1:
		till()
		till()
		plant(Entities.Cactus)
	NorthSorting()
	grid8[3] = measure(North)
	move(West)
	cacti_moving_95(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_moving_95(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	WestNorthEastSorting()
	grid7[3] = measure(North)
	move(South)
	cacti_moving_96(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_moving_96(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() > 7:
		till()
		till()
		plant(Entities.Cactus)
	NorthSorting()
	grid7[2] = measure(North)
	move(West)
	cacti_moving_97(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_moving_97(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() > 6:
		till()
		till()
		plant(Entities.Cactus)
	WestNorthEastSorting()
	grid6[2] = measure(North)
	move(South)
	cacti_moving_98(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_moving_98(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() > 5:
		till()
		till()
		plant(Entities.Cactus)
	NorthSorting()
	move(West)
	cacti_moving_99(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_moving_99(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() > 5:
		till()
		till()
		plant(Entities.Cactus)
	WestNorthEastSorting()
	grid4[0] = measure(West)
	grid5[9] = measure(South)
	grid5[1] = measure(North)
	move(East)
	cacti_moving_100(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_moving_100(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	NorthWestSorting()
	grid5[0] = measure(West)
	grid6[9] = measure(South)
	grid6[1] = measure(North)
	move(East)
	cacti_moving_101(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_moving_101(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() > 6:
		till()
		till()
		plant(Entities.Cactus)
	NorthWestSorting()
	grid6[0] = measure(West)
	grid7[9] = measure(South)
	move(East)
	cacti_moving_102(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_moving_102(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() > 7:
		till()
		till()
		plant(Entities.Cactus)
	WestSorting()
	grid7[0] = measure(West)
	grid8[9] = measure(South)
	move(North)
	cacti_moving_103(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_moving_103(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	SouthWestNorthSorting()
	grid7[1] = measure(West)
	move(East)
	cacti_moving_104(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_moving_104(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() < 1:
		till()
		till()
		plant(Entities.Cactus)
	WestSorting()
	move(North)
	cacti_moving_105(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_moving_105(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() < 2:
		till()
		till()
		plant(Entities.Cactus)
	SouthWestNorthSorting()
	grid8[2] = measure(West)
	grid0[2] = measure(East)
	grid9[3] = measure(North)
	move(South)
	cacti_moving_106(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_moving_106(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	NorthWestSorting()
	grid8[1] = measure(West)
	grid0[1] = measure(East)
	grid9[2] = measure(North)
	move(South)
	cacti_moving_107(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_moving_107(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	NorthWestSorting()
	grid8[0] = measure(West)
	grid0[0] = measure(East)
	grid9[9] = measure(South)
	grid9[1] = measure(North)
	grid9[0] = measure()
	move(East)