def cacti_move_0(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() > 4:
		till()
		till()
		plant(Entities.Cactus)
	move(North)
	cacti_move_1(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_1(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() > 4:
		till()
		till()
		plant(Entities.Cactus)
	SouthSort()
	move(East)
	cacti_move_2(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_2(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() > 4:
		till()
		till()
		plant(Entities.Cactus)
	WestSort()
	move(North)
	cacti_move_3(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_3(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() > 4:
		till()
		till()
		plant(Entities.Cactus)
	SouthSort()
	move(East)
	cacti_move_4(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_4(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() > 4:
		till()
		till()
		plant(Entities.Cactus)
	WestSort()
	move(North)
	cacti_move_5(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_5(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() > 5:
		till()
		till()
		plant(Entities.Cactus)
	SouthSort()
	move(East)
	cacti_move_6(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_6(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() > 5:
		till()
		till()
		plant(Entities.Cactus)
	WestSort()
	move(North)
	cacti_move_7(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_7(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() > 6:
		till()
		till()
		plant(Entities.Cactus)
	SouthSort()
	move(East)
	cacti_move_8(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_8(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() > 7:
		till()
		till()
		plant(Entities.Cactus)
	WestSort()
	move(North)
	cacti_move_9(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_9(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	SouthSort()
	move(East)
	cacti_move_10(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_10(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() < 1:
		till()
		till()
		plant(Entities.Cactus)
	WestSort()
	move(North)
	cacti_move_11(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_11(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() < 2:
		till()
		till()
		plant(Entities.Cactus)
	SouthSort()
	move(East)
	cacti_move_12(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_12(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() < 3:
		till()
		till()
		plant(Entities.Cactus)
	WestSort()
	move(North)
	cacti_move_13(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_13(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() < 4:
		till()
		till()
		plant(Entities.Cactus)
	SouthSort()
	move(East)
	cacti_move_14(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_14(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() < 4:
		till()
		till()
		plant(Entities.Cactus)
	WestSort()
	move(North)
	cacti_move_15(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_15(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() < 5:
		till()
		till()
		plant(Entities.Cactus)
	SouthSort()
	move(East)
	cacti_move_16(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_16(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() < 5:
		till()
		till()
		plant(Entities.Cactus)
	WestSort()
	move(North)
	cacti_move_17(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_17(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() < 5:
		till()
		till()
		plant(Entities.Cactus)
	SouthSort()
	move(West)
	cacti_move_18(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_18(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() < 5:
		till()
		till()
		plant(Entities.Cactus)
	SouthEastSort()
	move(South)
	cacti_move_19(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_19(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	NorthEastSouthSort()
	move(West)
	cacti_move_20(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_20(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() < 4:
		till()
		till()
		plant(Entities.Cactus)
	SouthEastSort()
	move(South)
	cacti_move_21(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_21(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	NorthEastSouthSort()
	move(West)
	cacti_move_22(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_22(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() < 3:
		till()
		till()
		plant(Entities.Cactus)
	SouthEastSort()
	move(South)
	cacti_move_23(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_23(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	NorthEastSouthSort()
	move(West)
	cacti_move_24(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_24(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() < 1:
		till()
		till()
		plant(Entities.Cactus)
	SouthEastSort()
	move(South)
	cacti_move_25(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_25(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	NorthEastSouthSort()
	move(West)
	cacti_move_26(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_26(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() > 7:
		till()
		till()
		plant(Entities.Cactus)
	SouthEastSort()
	move(South)
	cacti_move_27(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_27(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	NorthEastSouthSort()
	move(West)
	cacti_move_28(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_28(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() > 5:
		till()
		till()
		plant(Entities.Cactus)
	SouthEastSort()
	move(South)
	cacti_move_29(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_29(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	NorthEastSouthSort()
	move(West)
	cacti_move_30(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_30(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() > 4:
		till()
		till()
		plant(Entities.Cactus)
	SouthEastSort()
	move(South)
	cacti_move_31(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_31(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	NorthEastSouthSort()
	move(West)
	cacti_move_32(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_32(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() > 4:
		till()
		till()
		plant(Entities.Cactus)
	SouthEastSort()
	move(North)
	cacti_move_33(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_33(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() > 4:
		till()
		till()
		plant(Entities.Cactus)
	SouthEastSort()
	move(East)
	cacti_move_34(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_34(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	EastSouthWestSort()
	move(North)
	cacti_move_35(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_35(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() > 5:
		till()
		till()
		plant(Entities.Cactus)
	SouthEastSort()
	move(East)
	cacti_move_36(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_36(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	EastSouthWestSort()
	move(North)
	cacti_move_37(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_37(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() > 6:
		till()
		till()
		plant(Entities.Cactus)
	SouthEastSort()
	move(East)
	cacti_move_38(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_38(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	EastSouthWestSort()
	move(North)
	cacti_move_39(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_39(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	SouthEastSort()
	move(East)
	cacti_move_40(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_40(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	EastSouthWestSort()
	move(North)
	cacti_move_41(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_41(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() < 2:
		till()
		till()
		plant(Entities.Cactus)
	SouthEastSort()
	move(East)
	cacti_move_42(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_42(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	EastSouthWestSort()
	move(North)
	cacti_move_43(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_43(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() < 4:
		till()
		till()
		plant(Entities.Cactus)
	SouthEastSort()
	move(East)
	cacti_move_44(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_44(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	EastSouthWestSort()
	move(North)
	cacti_move_45(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_45(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() < 5:
		till()
		till()
		plant(Entities.Cactus)
	SouthEastSort()
	move(West)
	cacti_move_46(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_46(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() < 4:
		till()
		till()
		plant(Entities.Cactus)
	SouthEastSort()
	move(South)
	cacti_move_47(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_47(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	NorthEastSouthSort()
	grid6[8] = measure(East)
	move(West)
	cacti_move_48(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_48(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() < 3:
		till()
		till()
		plant(Entities.Cactus)
	SouthEastSort()
	move(South)
	cacti_move_49(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_49(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	NorthEastSouthSort()
	grid5[7] = measure(East)
	move(West)
	cacti_move_50(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_50(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() < 1:
		till()
		till()
		plant(Entities.Cactus)
	SouthEastSort()
	move(South)
	cacti_move_51(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_51(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	NorthEastSouthSort()
	grid4[6] = measure(East)
	move(West)
	cacti_move_52(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_52(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() > 7:
		till()
		till()
		plant(Entities.Cactus)
	SouthEastSort()
	move(South)
	cacti_move_53(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_53(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	NorthEastSouthSort()
	grid3[5] = measure(East)
	move(West)
	cacti_move_54(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_54(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() > 5:
		till()
		till()
		plant(Entities.Cactus)
	SouthEastSort()
	move(South)
	cacti_move_55(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_55(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	NorthEastSouthSort()
	grid2[4] = measure(East)
	grid1[3] = measure(South)
	move(West)
	cacti_move_56(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_56(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() > 4:
		till()
		till()
		plant(Entities.Cactus)
	SouthEastSort()
	move(North)
	cacti_move_57(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_57(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() > 5:
		till()
		till()
		plant(Entities.Cactus)
	SouthEastSort()
	move(East)
	cacti_move_58(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_58(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	EastSouthWestSort()
	grid1[4] = measure(South)
	move(North)
	cacti_move_59(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_59(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() > 6:
		till()
		till()
		plant(Entities.Cactus)
	SouthEastSort()
	move(East)
	cacti_move_60(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_60(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	EastSouthWestSort()
	grid2[5] = measure(South)
	move(North)
	cacti_move_61(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_61(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	SouthEastSort()
	move(East)
	cacti_move_62(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_62(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	EastSouthWestSort()
	grid3[6] = measure(South)
	move(North)
	cacti_move_63(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_63(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() < 2:
		till()
		till()
		plant(Entities.Cactus)
	SouthEastSort()
	move(East)
	cacti_move_64(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_64(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	EastSouthWestSort()
	grid5[8] = measure(East)
	grid4[7] = measure(South)
	move(North)
	cacti_move_65(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_65(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() < 4:
		till()
		till()
		plant(Entities.Cactus)
	SouthEastSort()
	move(West)
	cacti_move_66(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_66(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() < 3:
		till()
		till()
		plant(Entities.Cactus)
	SouthEastSort()
	move(South)
	cacti_move_67(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_67(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	NorthEastSouthSort()
	grid4[8] = measure(East)
	move(West)
	cacti_move_68(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_68(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() < 1:
		till()
		till()
		plant(Entities.Cactus)
	SouthEastSort()
	move(South)
	cacti_move_69(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_69(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	NorthEastSouthSort()
	grid3[7] = measure(East)
	move(West)
	cacti_move_70(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_70(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() > 7:
		till()
		till()
		plant(Entities.Cactus)
	SouthEastSort()
	move(South)
	cacti_move_71(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_71(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	NorthEastSouthSort()
	grid2[6] = measure(East)
	grid1[5] = measure(South)
	move(West)
	cacti_move_72(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_72(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() > 5:
		till()
		till()
		plant(Entities.Cactus)
	SouthEastSort()
	move(North)
	cacti_move_73(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_73(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() > 6:
		till()
		till()
		plant(Entities.Cactus)
	SouthEastSort()
	move(East)
	cacti_move_74(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_74(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	EastSouthWestSort()
	grid1[6] = measure(South)
	move(North)
	cacti_move_75(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_75(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	SouthEastSort()
	move(East)
	cacti_move_76(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_76(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	EastSouthWestSort()
	grid3[8] = measure(East)
	grid2[7] = measure(South)
	move(North)
	cacti_move_77(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_77(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() < 2:
		till()
		till()
		plant(Entities.Cactus)
	SouthEastSort()
	move(West)
	cacti_move_78(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_78(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() < 1:
		till()
		till()
		plant(Entities.Cactus)
	SouthEastSort()
	move(South)
	cacti_move_79(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_79(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	NorthEastSouthSort()
	grid2[8] = measure(East)
	grid1[7] = measure(South)
	move(West)
	cacti_move_80(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_80(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() > 7:
		till()
		till()
		plant(Entities.Cactus)
	SouthEastSort()
	grid1[8] = measure(East)
	move(North)
	cacti_move_81(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_81(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	SouthEastSort()
	move(West)
	cacti_move_82(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_82(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() < 5:
		till()
		till()
		plant(Entities.Cactus)
	WestSort()
	grid0[9] = measure(East)
	move(South)
	cacti_move_83(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_83(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() < 5:
		till()
		till()
		plant(Entities.Cactus)
	NorthWestSort()
	grid0[8] = measure(East)
	move(West)
	cacti_move_84(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_84(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	WestNorthEastSort()
	move(South)
	cacti_move_85(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_85(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() < 5:
		till()
		till()
		plant(Entities.Cactus)
	NorthWestSort()
	move(West)
	cacti_move_86(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_86(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	WestNorthEastSort()
	grid7[8] = measure(North)
	move(South)
	cacti_move_87(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_87(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() < 4:
		till()
		till()
		plant(Entities.Cactus)
	NorthWestSort()
	move(West)
	cacti_move_88(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_88(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	WestNorthEastSort()
	grid6[7] = measure(North)
	move(South)
	cacti_move_89(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_89(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() < 2:
		till()
		till()
		plant(Entities.Cactus)
	NorthWestSort()
	move(West)
	cacti_move_90(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_90(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	WestNorthEastSort()
	grid5[6] = measure(North)
	move(South)
	cacti_move_91(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_91(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	NorthWestSort()
	move(West)
	cacti_move_92(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_92(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	WestNorthEastSort()
	grid4[5] = measure(North)
	move(South)
	cacti_move_93(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_93(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() > 6:
		till()
		till()
		plant(Entities.Cactus)
	NorthWestSort()
	move(West)
	cacti_move_94(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_94(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	WestNorthEastSort()
	grid3[4] = measure(North)
	move(South)
	cacti_move_95(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_95(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() > 5:
		till()
		till()
		plant(Entities.Cactus)
	NorthWestSort()
	move(West)
	cacti_move_96(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_96(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	WestNorthEastSort()
	grid2[3] = measure(North)
	move(South)
	cacti_move_97(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_97(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() > 4:
		till()
		till()
		plant(Entities.Cactus)
	NorthWestSort()
	move(West)
	cacti_move_98(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_98(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	WestNorthEastSort()
	grid1[2] = measure(North)
	move(South)
	cacti_move_99(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_99(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() > 4:
		till()
		till()
		plant(Entities.Cactus)
	NorthWestSort()
	grid1[9] = measure(South)
	move(East)
	cacti_move_100(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_100(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() > 4:
		till()
		till()
		plant(Entities.Cactus)
	NorthWestSort()
	grid1[0] = measure(West)
	grid2[9] = measure(South)
	move(North)
	cacti_move_101(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_101(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	SouthWestNorthSort()
	grid1[1] = measure(West)
	move(East)
	cacti_move_102(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_102(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() > 4:
		till()
		till()
		plant(Entities.Cactus)
	NorthWestSort()
	move(North)
	cacti_move_103(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_103(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	SouthWestNorthSort()
	grid2[2] = measure(West)
	move(East)
	cacti_move_104(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_104(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() > 5:
		till()
		till()
		plant(Entities.Cactus)
	NorthWestSort()
	move(North)
	cacti_move_105(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_105(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	SouthWestNorthSort()
	grid3[3] = measure(West)
	move(East)
	cacti_move_106(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_106(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() > 7:
		till()
		till()
		plant(Entities.Cactus)
	NorthWestSort()
	move(North)
	cacti_move_107(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_107(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	SouthWestNorthSort()
	grid4[4] = measure(West)
	move(East)
	cacti_move_108(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_108(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() < 1:
		till()
		till()
		plant(Entities.Cactus)
	NorthWestSort()
	move(North)
	cacti_move_109(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_109(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	SouthWestNorthSort()
	grid5[5] = measure(West)
	move(East)
	cacti_move_110(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_110(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() < 3:
		till()
		till()
		plant(Entities.Cactus)
	NorthWestSort()
	move(North)
	cacti_move_111(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_111(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	SouthWestNorthSort()
	grid6[6] = measure(West)
	move(East)
	cacti_move_112(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_112(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() < 4:
		till()
		till()
		plant(Entities.Cactus)
	NorthWestSort()
	move(North)
	cacti_move_113(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_113(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	SouthWestNorthSort()
	grid7[7] = measure(West)
	grid8[8] = measure(North)
	move(East)
	cacti_move_114(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_114(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() < 5:
		till()
		till()
		plant(Entities.Cactus)
	NorthWestSort()
	grid0[7] = measure(East)
	grid9[8] = measure(North)
	move(South)
	cacti_move_115(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_115(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() < 5:
		till()
		till()
		plant(Entities.Cactus)
	NorthWestSort()
	grid0[6] = measure(East)
	grid9[7] = measure(North)
	move(West)
	cacti_move_116(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_116(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	WestNorthEastSort()
	grid8[7] = measure(North)
	move(South)
	cacti_move_117(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_117(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() < 4:
		till()
		till()
		plant(Entities.Cactus)
	NorthWestSort()
	move(West)
	cacti_move_118(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_118(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	WestNorthEastSort()
	grid7[6] = measure(North)
	move(South)
	cacti_move_119(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_119(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() < 2:
		till()
		till()
		plant(Entities.Cactus)
	NorthWestSort()
	move(West)
	cacti_move_120(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_120(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	WestNorthEastSort()
	grid6[5] = measure(North)
	move(South)
	cacti_move_121(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_121(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	NorthWestSort()
	move(West)
	cacti_move_122(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_122(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	WestNorthEastSort()
	grid5[4] = measure(North)
	move(South)
	cacti_move_123(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_123(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() > 6:
		till()
		till()
		plant(Entities.Cactus)
	NorthWestSort()
	move(West)
	cacti_move_124(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_124(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	WestNorthEastSort()
	grid4[3] = measure(North)
	move(South)
	cacti_move_125(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_125(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() > 5:
		till()
		till()
		plant(Entities.Cactus)
	NorthWestSort()
	move(West)
	cacti_move_126(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_126(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	WestNorthEastSort()
	grid2[1] = measure(West)
	grid3[2] = measure(North)
	move(South)
	cacti_move_127(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_127(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() > 4:
		till()
		till()
		plant(Entities.Cactus)
	NorthWestSort()
	grid2[0] = measure(West)
	grid3[9] = measure(South)
	move(East)
	cacti_move_128(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_128(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() > 4:
		till()
		till()
		plant(Entities.Cactus)
	NorthWestSort()
	grid3[0] = measure(West)
	grid4[9] = measure(South)
	move(North)
	cacti_move_129(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_129(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	SouthWestNorthSort()
	grid3[1] = measure(West)
	move(East)
	cacti_move_130(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_130(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() > 5:
		till()
		till()
		plant(Entities.Cactus)
	NorthWestSort()
	move(North)
	cacti_move_131(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_131(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	SouthWestNorthSort()
	grid4[2] = measure(West)
	move(East)
	cacti_move_132(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_132(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() > 7:
		till()
		till()
		plant(Entities.Cactus)
	NorthWestSort()
	move(North)
	cacti_move_133(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_133(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	SouthWestNorthSort()
	grid5[3] = measure(West)
	move(East)
	cacti_move_134(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_134(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() < 1:
		till()
		till()
		plant(Entities.Cactus)
	NorthWestSort()
	move(North)
	cacti_move_135(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_135(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	SouthWestNorthSort()
	grid6[4] = measure(West)
	move(East)
	cacti_move_136(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_136(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() < 3:
		till()
		till()
		plant(Entities.Cactus)
	NorthWestSort()
	move(North)
	cacti_move_137(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_137(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	SouthWestNorthSort()
	grid7[5] = measure(West)
	grid8[6] = measure(North)
	move(East)
	cacti_move_138(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_138(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() < 4:
		till()
		till()
		plant(Entities.Cactus)
	NorthWestSort()
	grid0[5] = measure(East)
	grid9[6] = measure(North)
	move(South)
	cacti_move_139(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_139(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() < 4:
		till()
		till()
		plant(Entities.Cactus)
	NorthWestSort()
	grid0[4] = measure(East)
	grid9[5] = measure(North)
	move(West)
	cacti_move_140(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_140(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	WestNorthEastSort()
	grid8[5] = measure(North)
	move(South)
	cacti_move_141(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_141(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() < 2:
		till()
		till()
		plant(Entities.Cactus)
	NorthWestSort()
	move(West)
	cacti_move_142(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_142(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	WestNorthEastSort()
	grid7[4] = measure(North)
	move(South)
	cacti_move_143(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_143(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	NorthWestSort()
	move(West)
	cacti_move_144(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_144(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	WestNorthEastSort()
	grid6[3] = measure(North)
	move(South)
	cacti_move_145(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_145(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() > 6:
		till()
		till()
		plant(Entities.Cactus)
	NorthWestSort()
	move(West)
	cacti_move_146(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_146(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	WestNorthEastSort()
	grid4[1] = measure(West)
	grid5[2] = measure(North)
	move(South)
	cacti_move_147(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_147(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() > 5:
		till()
		till()
		plant(Entities.Cactus)
	NorthWestSort()
	grid4[0] = measure(West)
	grid5[9] = measure(South)
	move(East)
	cacti_move_148(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_148(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() > 5:
		till()
		till()
		plant(Entities.Cactus)
	NorthWestSort()
	grid5[0] = measure(West)
	grid6[9] = measure(South)
	move(North)
	cacti_move_149(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_149(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	SouthWestNorthSort()
	grid5[1] = measure(West)
	move(East)
	cacti_move_150(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_150(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() > 7:
		till()
		till()
		plant(Entities.Cactus)
	NorthWestSort()
	move(North)
	cacti_move_151(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_151(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	SouthWestNorthSort()
	grid6[2] = measure(West)
	move(East)
	cacti_move_152(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_152(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() < 1:
		till()
		till()
		plant(Entities.Cactus)
	NorthWestSort()
	move(North)
	cacti_move_153(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_153(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	SouthWestNorthSort()
	grid7[3] = measure(West)
	grid8[4] = measure(North)
	move(East)
	cacti_move_154(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_154(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() < 3:
		till()
		till()
		plant(Entities.Cactus)
	NorthWestSort()
	grid0[3] = measure(East)
	grid9[4] = measure(North)
	move(South)
	cacti_move_155(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_155(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() < 2:
		till()
		till()
		plant(Entities.Cactus)
	NorthWestSort()
	grid0[2] = measure(East)
	grid9[3] = measure(North)
	move(West)
	cacti_move_156(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_156(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	WestNorthEastSort()
	grid8[3] = measure(North)
	move(South)
	cacti_move_157(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_157(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	NorthWestSort()
	move(West)
	cacti_move_158(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_158(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	WestNorthEastSort()
	grid6[1] = measure(West)
	grid7[2] = measure(North)
	move(South)
	cacti_move_159(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_159(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() > 6:
		till()
		till()
		plant(Entities.Cactus)
	NorthWestSort()
	grid6[0] = measure(West)
	grid7[9] = measure(South)
	move(East)
	cacti_move_160(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_160(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() > 7:
		till()
		till()
		plant(Entities.Cactus)
	NorthWestSort()
	grid7[0] = measure(West)
	grid8[9] = measure(South)
	move(North)
	cacti_move_161(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_161(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	SouthWestNorthSort()
	grid7[1] = measure(West)
	grid8[2] = measure(North)
	move(East)
	cacti_move_162(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_162(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	while measure() < 1:
		till()
		till()
		plant(Entities.Cactus)
	NorthWestSort()
	grid8[1] = measure(West)
	grid0[1] = measure(East)
	grid9[2] = measure(North)
	move(South)
	cacti_move_163(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9)
def cacti_move_163(grid0, grid1, grid2, grid3, grid4, grid5, grid6, grid7, grid8, grid9):
	till()
	plant(Entities.Cactus)
	NorthWestSort()
	grid8[0] = measure(West)
	grid0[0] = measure(East)
	grid9[9] = measure(South)
	grid9[1] = measure(North)
	grid9[0] = measure()
	move(East)