def stage0v2():
    
    # i = 0
    # for i in range(100):
        #if can_harvest():
        # harvest()
        # i += 1



    harvest()
    harvest()
    harvest()
    harvest()
    harvest()
    harvest()
    harvest()
    harvest()
    harvest()
    harvest()
    harvest()
    harvest()
    harvest()
    harvest()
    harvest()
    harvest()
    harvest()
    harvest()
    harvest()
    harvest()
    harvest()
    harvest()
    harvest()
    harvest()
    harvest()
    harvest()
    harvest()
    harvest()
    harvest()
    harvest()
    harvest()
    harvest()
    harvest()
    harvest()
    harvest()
    harvest()
    harvest()
    harvest()
    harvest()
    harvest()
    harvest()
    harvest()
    harvest()
    harvest()
    harvest()
    harvest()
    harvest()
    harvest()
    harvest()
    harvest()
    harvest()
    harvest()
    harvest()
    harvest()
    harvest()
    harvest()
    harvest()
    harvest()
    harvest()
    harvest()
    harvest()
    harvest()
    harvest()
    harvest()
    harvest()
    harvest()
    harvest()
    harvest()
    harvest()
    harvest()
    harvest()
    harvest()
    harvest()
    harvest()
    harvest()
    harvest()
    harvest()
    harvest()
    harvest()
    harvest()
    harvest()
    harvest()
    harvest()
    harvest()
    harvest()
    harvest()
    harvest()
    harvest()
    harvest()
    harvest()
    harvest()
    harvest()
    harvest()
    harvest()
    harvest()
    harvest()
    harvest()
    unlock(Unlocks.Speed)
    harvest()
    unlock(Unlocks.Plant)
    harvest()
    unlock(Unlocks.Expand)
    harvest()

    plant(Entities.Bush)
    move(North)
    harvest()
    plant(Entities.Bush)
    move(North)
    harvest()
    for i in range(10):
        while not can_harvest():
            